- name: pull branch master
  git:
    repo: '{{ repo_url }}/{{ repo }}.git'
    dest: '{{ repo_dir }}'
    accept_hostkey: yes

- name: install virtualenv
  shell: 'virtualenv --python=python3 {{ home_dir }}/venv'

- name: install python requirements
  pip: 
    requirements: '{{ repo_dir }}/requirements/production.txt'
    virtualenv: '{{ home_dir }}/venv'
    virtualenv_python: python3
    extra_args: --upgrade

- name: create static_root dir
  file: 
    path: '{{ static_dir }}' 
    state: directory 
    mode: 0755

- name: create run dir
  file:
      path: '{{ django_dir }}/run'
      state: directory
      mode: 0755

- name: touch SECRET.key file
  file:
      path: '{{ django_dir }}/run/SECRET.key'
      state: touch
      mode: '755'

- name: chmod +w SECRET.key
  shell: 'chmod +w {{ django_dir }}/run/SECRET.key'

- name: add database URL to settings file
  lineinfile:
      path: '{{ django_dir }}/northwood/settings/production.py'
      line: 'DATABASES["default"] = dj_database_url.config(default="{{ database_url }}")'
      state: present
      
- name: django collectstatic
  shell: 'source {{ home_dir }}/venv/bin/activate && {{ django_dir }}/manage.py collectstatic --no-input'
  args:
    executable: /bin/bash

- name: django migrate
  shell: 'source {{ home_dir }}/venv/bin/activate && {{ django_dir }}/manage.py migrate --no-input'
  args:
    executable: /bin/bash

    #- name: django loaddata
    #  shell: 'source {{ home_dir }}/venv/bin/activate && {[ django_dir }}/manage.py loaddata user'
    #  args:
    #    executable: /bin/bash

- name: uwsgi restart
  service: 
    name: uwsgi 
    state: restarted
