- shell: echo "$USER"

- ipify_facts:

- name: Enable universe repository
  apt_repository:
    repo: '{{ item }}'
  loop:
     - "deb http://archive.ubuntu.com/ubuntu/ bionic universe"
     - "deb http://archive.ubuntu.com/ubuntu/ bionic-updates universe"
     - "deb http://security.ubuntu.com/ubuntu/ bionic-security universe"

- name: Running apt update
  apt: 
    update_cache: yes

- name: Installing required packages
  apt: 
    name: 
      - fail2ban
      - python3-dev
      - python3-pip
      - virtualenv
      - default-libmysqlclient-dev
      - git
      - rdiff-backup
      - libpq-dev
      - python-psycopg2
      - uwsgi
      - uwsgi-plugin-python
      - nginx
    state: present
