- hosts: northwood
  become: true
  vars_files:
      - host_vars/northwood
      - '/tmp/packer/{{ packer_builder_type }}.yml'
  environment:
      DJANGO_SETTINGS_MODULE: '{{ django_project }}.settings.production'
      DATABASE_URL: '{{ database_url }}'
      STATIC_ROOT: '{{ static_dir }}'
  roles:
      - ansible-role-mysql-master
      - django_server
